
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jhonyrg.dev.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CREATE = 5;
  public static final int keyword = 2;
  public static final int identifier = 3;
  public static final int error = 1;
  public static final int DATABASE = 6;
  public static final int SEMI = 7;
  public static final int symbol = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "keyword",
  "identifier",
  "symbol",
  "CREATE",
  "DATABASE",
  "SEMI"
  };
}

